JMS Demo entry
--------------

link:jms-helloworld.asciidoc[JMS helloworld demo entry]

link:jms-jbossmessaging-clusterPullConnectionFactoryName.asciidoc[JMS JBossMessaging ServerPeer ClusterPullConnectionFactoryName attribute test demo entry]

link:jms-spring-integration.asciidoc[JMS Spring Integration demo entry]


How to add a JMS destination against on JBoss EAP 6 & JBoss AS 7?
-----------------------------------------------------------------


* We can use the following 4 ways to add JMS destionation on JBoss EAP 6 or JBoss AS 7
** Management Console
** Management CLI
** Deploy *-jms.xml file to deployments folder
** Edit JBoss Configuration file


Using Management Console:
+++++++++++++++++++++++++

* Start Message-Enable JBoss instance, for example start JBoss with `-c` or `--server-config=` point to standalone-full.xml if use standalone mode
----
./standalone.sh -c standalone-full.xml
----

* Navigate to Management Console(http://localhost:9990/console), Profile -> Messaging -> Destinations -> default -> View, then click add button


Using Management CLI:
+++++++++++++++++++++

* Connect to JBoss CLI
----
./jboss-cli.sh
----

* Come into the messaging subsystem:
----
cd /subsystem=messaging/hornetq-server=default
----

* execute add operation
----
./jms-queue=testQueue:add(durable=false,entries=["java:jboss/exported/jms/queue/test"])
----


Deploying *-jms.xml file to deployments folder:
+++++++++++++++++++++++++++++++++++++++++++++++

* create a file named `sample-jms.xml`, the content should be look like the following, add `sample-jms.xml` to JBoss deployments folder, do deploy.
----
<?xml version="1.0" encoding="UTF-8"?>
<messaging-deployment xmlns="urn:jboss:messaging-deployment:1.0">
    <hornetq-server>
        <jms-destinations>
            <jms-queue name="testQueue">
                <entry name="queue/test"/>
                <entry name="java:jboss/exported/jms/queue/test"/>
            </jms-queue>
            <jms-topic name="testTopic">
                <entry name="topic/test"/>
                <entry name="java:jboss/exported/jms/topic/test"/>
            </jms-topic>
        </jms-destinations>
    </hornetq-server>
</messaging-deployment>
----

* Note that JBOSS_HOME/docs/schema/jboss-as-messaging-deployment_1_0.xsd is schema file for deploying jms destionation via deployment file


Editing JBoss Configuration file, use standalone-full.xml as example:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

* Open the file: JBOSS_HOME/standalone/configuration/standalone-full.xml

* Find the messaging subsystem: 
----
<subsystem xmlns="urn:jboss:domain:messaging:1.2">
----

* Scroll to the end of this section and add the following XML after the </jms-connection-factories> end tag but before the </hornetq-server> element:
----
<jms-destinations>
        <jms-queue name="testQueue">
            <entry name="queue/test"/>
            <entry name="java:jboss/exported/jms/queue/test"/>
        </jms-queue>
        <jms-topic name="testTopic">
            <entry name="topic/test"/>
            <entry name="java:jboss/exported/jms/topic/test"/>
        </jms-topic>
    </jms-destinations>
----

* Save the changes and close the file. 



How to add an Application User?
-------------------------------
* Open a command line

* Type the command for your operating system
----
For Linux:   JBOSS_HOME/bin/add-user.sh
For Windows: JBOSS_HOME\bin\add-user.bat
----

* You should see the following response:
----
What type of user do you wish to add? 

a) Management User (mgmt-users.properties) 
b) Application User (application-users.properties)
(a):
---- 
At the prompt, type: b

* You should see the following response:
----
Enter the details of the new user to add.
Realm (ApplicationRealm) : 
----
If we want to specify a realm, type it here. Otherwise, press enter to use the default `ApplicationRealm`

* When prompted, enter the the Username and Passord.
----
Username : kylin
Password : 
Re-enter Password : 
----

* At the next prompt, you will be asked "What roles do you want this user to belong to?"
----
What roles do you want this user to belong to? (Please enter a comma separated list, or leave blank for none)[  ]: 
----
type `guest` if tyou do not specify a role
